# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: WebDriver IO Tests

on:
  push:
    branches: [ "main", "homeWork" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '30 18 * * *'  

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Run WebDriver IO tests
      run: npx wdio run ./wdio.conf.js
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 5

